blank_issues_enabled: false
contact_links:
  - name: Security issue
    url: https://github.com/Cobracco/home-assistant-aruba-ddns/security/policy
    about: Reporta vulnerabilita seguendo la security policy.
